#spring.application.name=briskSpringDemo

spring:
  application:
    name: briskSpringDemo
  threads:
    virtual:
      enabled: true
  config:
    import: optional:credentials.yaml
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    use-root-path: true
resilience4j:
  ratelimiter:
    instances:
      briskSpringDemo:
        limit-for-period: 10
        limit-refresh-period:
          10000
        timeout-duration:
          10000
server:
  port: 9090

grpc:
  server:
    port: 9091
  client:
    server:
      host: localhost
      port: 9091